server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/hotel
    username: root
    password: Udipta@18
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:9296  
    
      
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#   fetch-registry: true
#   register-with-eureka: true
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}  